
### GET specific country (external)
GET https://restcountries.com/v3.1/name/sweden

### GET all countries within a region (external)
GET https://restcountries.com/v3.1/region/europe


### GET all countries within a region (including external)
GET http://localhost:4000/api/external/region/europe

### GET specific country (including external)
GET http://localhost:4000/api/external/country/canada





### GET all notes
GET http://localhost:4000/api/notes


### GET all notes on specific country
GET http://localhost:4000/api/notes/China


### GET specific note by id
GET http://localhost:4000/api/note/1


### POST not working atm
POST http://localhost:4000/api/notes