
### GET all countries (external)
GET https://restcountries.com/v3.1/all

### GET specific country (external)
GET https://restcountries.com/v3.1/name/sweden

### GET all countries within a region (external)
GET https://restcountries.com/v3.1/region/europe



### GET all countries (including external)
GET http://localhost:4000/api/external/all

### GET all countries within a region (including external)
GET http://localhost:4000/api/external/region/europe

### GET specific country (including external)
GET http://localhost:4000/api/external/country/canada





### GET all notes
GET http://localhost:4000/api/notes


### GET all notes on specific country
GET http://localhost:4000/api/notes/country/Sweden


### GET specific note by id
GET http://localhost:4000/api/notes/bhjbjhbbjh


### POST Creates new note
POST http://localhost:4000/api/notes
Content-Type: application/json

{
    "country": "Norway",
    "city": "Oslo",
    "name": "Ange",
    "comment": "Goa gubbar där också!"
}


### PUT - Change note 
PUT http://localhost:4000/api/notes
Content-Type: application/json

{   
    "id": "jnIY-apoWUBHfiOLJOmxN",
    "country": "Norway",
    "city": "Oslo",
    "name": "Ange",
    "comment": "Inte så goa gubbar längre",
    "date": "2022-08-18"
}



### DELETE 
DELETE  http://localhost:4000/api/notes/jnIY-apoWUBHfiOLJOmxN