
### GET all countries (external)
GET https://restcountries.com/v3.1/all

### GET specific country (external)
GET https://restcountries.com/v3.1/name/sweden

### GET all countries within a region (external)
GET https://restcountries.com/v3.1/region/europe



### GET all countries (including external)
GET http://localhost:4000/api/external/all

### GET all countries within a region (including external)
GET http://localhost:4000/api/external/region/europe

### GET specific country (including external)
GET http://localhost:4000/api/external/country/canada





### GET all notes
GET http://localhost:4000/api/notes


### GET all notes on specific country
GET http://localhost:4000/api/notes/country/China


### GET specific note by id
GET http://localhost:4000/api/notes/BSAPicl5ct_d4MvyrA1QX


### POST Creates new note
POST http://localhost:4000/api/notes
Content-Type: application/json

{
    "country": "Norge",
    "city": "Oslo",
    "name": "Ange",
    "comment": "Goa gubbar där också!"
}


### PUT - Change note // Inte fixad än
PUT http://localhost:4000/api/notes
Content-Type: application/json

{   
    "id": "3hF7MXSpDmJ2Eu_2GBn5W",
    "country": "Norge",
    "city": "Oslo",
    "name": "Ange",
    "comment": "Inte så goa gubbar längre"
}



### DELETE 
DELETE  http://localhost:4000/api/notes/BSAPicl5ct_d4MvyrA1QX